name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or the version specified by Docusaurus

      - name: Install Stencil Dependencies
        run: npm ci

      - name: Create Stencil Docs
        run: npm run build-docs

      - name: List assets
        run: ls -la docs/static

      # Install dependencies
      - name: Install Docusaurus Dependencies
        run: cd docs && npm ci

      # Build the site
      - name: Build Docusaurus site
        run: cd docs && npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
